version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # ホストのポート:コンテナのポート
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app_network
    env_file:
      - .env

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"  # ホストのポート:コンテナのポート
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
#      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - app_network
    env_file:
      - .env

networks:
  app_network:

#volumes:
#  postgres_data:

