version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"  # ホストのポート:コンテナのポート
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:latest
    ports:
      - "5432:5432"  # ホストのポート:コンテナのポート
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # init.sqlをマウント
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:

